import { chromium } from 'playwright'
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] })
const page = await browser.newPage({ viewport: { width: 1400, height: 800 } })
page.on('console', (m) => { if (m.type() === 'error') console.log('console.error', m.text().slice(0, 300)) })
await page.goto('http://127.0.0.1:5185/?season=summer#braddock-i70', { waitUntil: 'load' })
await page.waitForFunction(() => document.querySelector('#status')?.textContent === '' && window.corridor, null, { timeout: 180000 })
await page.keyboard.press('d')
await page.evaluate(() => { window.corridor.drive.lane = -21; window.corridor.drive.speed = 0; window.corridor.drive.yaw = 0.35 })
await page.waitForTimeout(2500)
await page.screenshot({ path: process.argv[2], timeout: 120000 })
await browser.close()
