// Where the dressing goes on a building.
//
// Rich, 2026-09-28: "a buildings dressing kit for windows, doors, gutters, driveways, other common
// architectural features — something we could attach to autogenerated buildings to make them feel
// alive."
//
// `buildings.ts` draws MASSING — a ring extruded to the height lidar measured, with a gable on
// anything house-sized. That reads as a street from a moving car and as a cardboard model from the
// pavement, because a real building is mostly its openings. This works out where the openings and
// the trim go.
//
// PURE GEOMETRY, NO THREE, NO MESHES. It takes a footprint and returns a list of sites — a
// position, a facing, and which part of the kit belongs there. What fills them is a separate
// question with a separate failure mode: a site plan that is wrong looks like a house with a door
// in the middle of a blank wall, and that has to be diagnosable without a GPU or a generated mesh.
//
// THE STREET DECIDES EVERYTHING. Which wall gets the front door, where the driveway meets, which
// side the meter box hides on — all of it follows from which face looks at the road, so that is
// the first thing computed and every other rule is relative to it. A building dressed without a
// street reference is a building with four backs.
//
// Site frame throughout: x east, y north, z up. Yaw is 0 facing north (+y), matching Transform.

/** A part of the kit, as `tools/assetlib/specs/buildings-dressing.json` declares it. */
export interface DressingPart {
  id: string
  attach: {
    to: 'wall' | 'wall-corner' | 'roof' | 'roof-edge' | 'roof-ridge' | 'ground'
    opening?: boolean
    widthM?: number
    heightM?: number
    lengthM?: number
    depthM?: number
    sillM?: number
    projectionM?: number
    diameterM?: number
    profileM?: number
    repeat?: 'single' | 'row' | 'grid' | 'run' | 'storey'
    tile?: boolean
    at?: 'entrance' | 'garage' | 'side'
    storey?: 'ground' | 'upper'
    meets?: string
  }
}

/** A building, as `manifest.buildings` gives it. */
export interface Footprint {
  ring: [number, number][]
  height_m?: number
  area_m2?: number
  /** minimum rotated rectangle, as the bake writes it. yaw_deg is CCW from east, along the long axis. */
  rect?: { w: number; d: number; yaw_deg: number } | null
  /** OSM building= value, when the bake kept one */
  kind?: string | null
}

/** One placement: what goes there, where, and which way it faces. */
export interface DressingSite {
  part: string
  /** site metres — x east, y north, z up. For a wall part, the centre of the part ON the wall face. */
  at: [number, number, number]
  /** radians; a wall part faces outward along its wall's normal */
  yaw: number
  /** how wide to draw it. A run (gutter, ridge vent) reports the whole run and tiles along it. */
  width: number
  height: number
  /** which wall it sits on, or -1 for a roof or free-standing ground part */
  wall: number
  /** cut a hole in the wall here before drawing the part */
  opening: boolean
  /** on the wall that faces the street — the only elevation anybody looks at closely */
  front: boolean
}

type Wall = { a: [number, number]; b: [number, number]; len: number; yaw: number; mid: [number, number] }

const dist = (a: [number, number], b: [number, number]) => Math.hypot(b[0] - a[0], b[1] - a[1])

/** Outward normal of a wall, from its yaw. */
export function normalOf(yaw: number): [number, number] {
  return [Math.sin(yaw), Math.cos(yaw)]
}

/**
 * Each usable wall of a ring: ends, length, outward normal as a yaw, midpoint.
 *
 * The ring is wound counter-clockwise first so the outward normal is a consistent turn; OSM gives
 * both windings and half a street dressed inside-out is the result of assuming one.
 */
export function walls(ring: [number, number][]): Wall[] {
  const out: Wall[] = []
  const area = ring.reduce((s, [x0, y0], i) => {
    const [x1, y1] = ring[(i + 1) % ring.length]
    return s + (x0 * y1 - x1 * y0)
  }, 0)
  const r = area < 0 ? [...ring].reverse() : ring
  for (let i = 0; i < r.length; i += 1) {
    const a = r[i]
    const b = r[(i + 1) % r.length]
    const len = dist(a, b)
    // a ring simplified from OSM keeps slivers; nothing is dressed on a 20 cm wall
    if (len < 0.5) continue
    // yaw of the edge direction, turned RIGHT: on a counter-clockwise ring that is the outward
    // side. Turning the other way gives a plan that is perfectly self-consistent and inside out.
    out.push({ a, b, len, yaw: Math.atan2(b[0] - a[0], b[1] - a[1]) + Math.PI / 2, mid: [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2] })
  }
  return out
}

/**
 * Which wall faces the street.
 *
 * Whichever wall's outward normal points most nearly at the road, weighted towards the near ones.
 * NOT simply the nearest wall: on a corner plot the nearest wall is often the side, and a front
 * door on the side of a house is the most obvious way this can be wrong. Not purely by normal
 * either, or a long back wall parallel to the road out-scores the short front.
 */
export function frontWall(ring: [number, number][], street: [number, number] | null): number {
  const w = walls(ring)
  if (!w.length) return -1
  // no street: the longest wall, which is the usual frontage and is at least stable across loads
  if (!street) return w.reduce((best, x, i) => (x.len > w[best].len ? i : best), 0)
  let best = 0
  let bestScore = -Infinity
  for (let i = 0; i < w.length; i += 1) {
    const to: [number, number] = [street[0] - w[i].mid[0], street[1] - w[i].mid[1]]
    const d = Math.hypot(to[0], to[1]) || 1e-6
    const n = normalOf(w[i].yaw)
    const facing = (to[0] / d) * n[0] + (to[1] / d) * n[1]
    // facing dominates; nearness only separates two walls that both look at the road
    const score = facing - d / 200
    if (score > bestScore) { bestScore = score; best = i }
  }
  return best
}

/**
 * Evenly spaced centres along a run of `len`, for items `width` wide.
 *
 * `inset` keeps an opening off the corner, because a window frame running into the return of the
 * wall is the other obvious tell. The count is whatever fits at no closer than `minGap`; a wall
 * too short for one gets none rather than one squeezed in.
 */
export function spaceAlong(len: number, width: number, { inset = 0.6, minGap = 0.8, max = 64 } = {}): number[] {
  const usable = len - inset * 2
  if (!(usable >= width) || !(width > 0)) return []
  const n = Math.min(max, Math.max(1, Math.floor((usable + minGap) / (width + minGap))))
  const span = n * width + (n - 1) * minGap
  const start = inset + (usable - span) / 2 + width / 2
  return Array.from({ length: n }, (_, i) => start + i * (width + minGap))
}

/** A point `t` metres along a wall from its first end, pushed `out` metres off its face. */
export function onWall(w: Wall, t: number, out = 0): [number, number] {
  const dx = (w.b[0] - w.a[0]) / w.len
  const dy = (w.b[1] - w.a[1]) / w.len
  const n = normalOf(w.yaw)
  return [w.a[0] + dx * t + n[0] * out, w.a[1] + dy * t + n[1] * out]
}

export type BuildingClass = 'house' | 'commercial' | 'block' | 'shed'

/**
 * What kind of building this is, which decides which half of the kit applies.
 *
 * A storefront on a bungalow and a double-hung window on a warehouse are the two ways to make a
 * street look wrong, so this runs before any placement. OSM's `building=` tag wins where the bake
 * kept one; otherwise it is footprint and height, which is all lidar gives.
 */
export function classify(b: Footprint): BuildingClass {
  const h = b.height_m ?? 6
  const area = b.area_m2 ?? 0
  const k = (b.kind ?? '').toLowerCase()
  if (/^(house|detached|semidetached|residential|bungalow|terrace|hut|cabin)/.test(k)) return h > 12 ? 'block' : 'house'
  if (/^(retail|commercial|shop|supermarket|office|industrial|warehouse|civic|school|church)/.test(k)) return h > 12 ? 'block' : 'commercial'
  if (/^(shed|garage|carport|roof|greenhouse)/.test(k)) return 'shed'
  if (area > 0 && area < 25) return 'shed'
  if (h > 12) return 'block'
  if (h < 3.2 && area < 60) return 'shed'
  if (area > 600) return 'commercial'
  return 'house'
}

export interface PlanOpts {
  /** the nearest point of road, in site metres. Without it the longest wall is treated as front. */
  street?: [number, number] | null
  /** ground height under the footprint */
  base?: number
  /** storey height; 3 m domestic, and what "upper" means for a fire escape */
  storeyM?: number
  /**
   * How many elevations get windows: the street-facing one first, then the longest.
   *
   * THE COST KNOB, and it is not a small one. Dressing every wall of crofton-triangle's 7506
   * footprints plans 138,532 windows — 555k triangles of glass, most of it on the back of a house
   * with another house behind it. Measured, not guessed (probes/_zzcount.mjs). 4 is everything.
   */
  windowWalls?: number
}

/** Storeys at `storeyM` each — a bungalow gets one row of windows, a three-storey block three. */
export function storeysOf(height: number, storeyM = 3): number {
  return Math.max(1, Math.round(height / storeyM))
}

/**
 * Work out where every part of the kit goes on one building.
 *
 * Deterministic: same footprint, same plan, every load. A house that is dressed differently each
 * time is a house that flickers, so nothing here reads a random source — the only asymmetry (which
 * third of the facade the door sits in) comes from the footprint's own coordinates.
 */
export function planDressing(b: Footprint, kit: DressingPart[], opts: PlanOpts = {}): DressingSite[] {
  const ring = b.ring ?? []
  if (ring.length < 3) return []
  const w = walls(ring)
  if (!w.length) return []

  const base = opts.base ?? 0
  const storeyM = opts.storeyM ?? 3
  const height = Math.max(2.2, b.height_m ?? 6)
  const street = opts.street ?? null
  const front = frontWall(ring, street)
  const cls = classify(b)

  // THE WALL IS NOT THE BUILDING. `buildings.ts` gables anything house-sized, and on a gable the
  // wall stops at 0.7 h and the roof takes the rest. Sizing windows against the full height puts
  // the upper row through the roof slope, so the same test runs here and everything vertical —
  // storeys, sills, the gutter line, the downpipe — measures against the wall, not the ridge.
  const rect = b.rect ?? null
  const area = b.area_m2 ?? 0
  const gabled = !!rect && area > 25 && area < 500 && height < 12 && rect.d > 3
  const wallTop = gabled ? height * 0.7 : height

  const storeys = storeysOf(wallTop, storeyM)
  const sites: DressingSite[] = []
  const by = (id: string) => kit.find((p) => p.id === id)

  const put = (p: DressingPart | undefined, at: [number, number, number], yaw: number, wall: number, size?: { w?: number; h?: number }) => {
    if (!p) return
    sites.push({
      part: p.id,
      at,
      yaw,
      front: wall === front,
      width: size?.w ?? p.attach.widthM ?? p.attach.lengthM ?? p.attach.diameterM ?? 1,
      height: size?.h ?? p.attach.heightM ?? p.attach.profileM ?? 1,
      wall,
      opening: !!p.attach.opening,
    })
  }

  // reserved spans per wall, as [from, to] metres along it, so two parts never share a hole
  const taken: Map<number, [number, number][]> = new Map()
  const reserve = (i: number, from: number, to: number) => {
    const list = taken.get(i) ?? []
    list.push([from, to])
    taken.set(i, list)
  }
  const free = (i: number, t: number, width: number) => {
    const from = t - width / 2
    const to = t + width / 2
    return !(taken.get(i) ?? []).some(([f, x]) => to > f - 0.4 && from < x + 0.4)
  }

  /* ---- the front door, and the garage beside it ------------------------------------------ */
  const fw = front >= 0 ? w[front] : null
  if (fw && cls !== 'shed') {
    const door = cls === 'commercial' || cls === 'block' ? by('door-front-panelled') : by('door-front-panelled')
    const dw = door?.attach.widthM ?? 0.91
    // a third along rather than centred: a door in the exact middle reads as civic, and almost no
    // house is symmetrical. Which third is fixed by the wall's own direction, not a random draw.
    const flip = fw.a[0] + fw.a[1] < fw.b[0] + fw.b[1]
    const t = Math.min(fw.len - dw / 2 - 0.4, Math.max(dw / 2 + 0.4, fw.len * (flip ? 0.32 : 0.68)))
    put(door, [...onWall(fw, t), base] as [number, number, number], fw.yaw, front)
    reserve(front, t - dw / 2, t + dw / 2)

    const step = by('porch-step-concrete')
    if (step) put(step, [...onWall(fw, t), base] as [number, number, number], fw.yaw, front)
    const box = by('mailbox-wall-mounted')
    if (box && cls === 'house') {
      const bt = t + dw / 2 + 0.45
      if (bt < fw.len - 0.3) {
        put(box, [...onWall(fw, bt), base + (box.attach.sillM ?? 1.3)] as [number, number, number], fw.yaw, front)
        reserve(front, bt - 0.2, bt + 0.2)
      }
    }

    // a garage on a house wide enough to have one, at the far end of the frontage from the door
    const garage = by('door-garage-sectional')
    if (garage && cls === 'house' && fw.len > 9) {
      const gw = garage.attach.widthM ?? 2.9
      const gt = flip ? fw.len - gw / 2 - 0.6 : gw / 2 + 0.6
      if (free(front, gt, gw)) {
        put(garage, [...onWall(fw, gt), base] as [number, number, number], fw.yaw, front)
        reserve(front, gt - gw / 2, gt + gw / 2)
        const drive = by('driveway-concrete-apron')
        if (drive) {
          // it runs from the garage door out to the road, so it is as long as that gap, not the
          // nominal 6 m: an apron that stops short of the kerb is worse than none
          const n = normalOf(fw.yaw)
          const reach = street
            ? Math.max(2, (street[0] - onWall(fw, gt)[0]) * n[0] + (street[1] - onWall(fw, gt)[1]) * n[1])
            : (drive.attach.lengthM ?? 6)
          put(drive, [...onWall(fw, gt, reach / 2), base] as [number, number, number], fw.yaw, front, { w: Math.max(gw, drive.attach.widthM ?? 5), h: reach })
        }
      }
    }
  }

  /* ---- windows ---------------------------------------------------------------------------- */
  const shopfront = cls === 'commercial' || cls === 'block'
  // which elevations get glass: the street's first, then the longest, up to the budget
  const order = w.map((_x, i) => i).sort((a, c) => (a === front ? -1 : c === front ? 1 : w[c].len - w[a].len))
  const glazed = new Set(order.slice(0, Math.max(1, Math.min(w.length, Math.round(opts.windowWalls ?? 4)))))
  const store = by('window-commercial-storefront')
  const hung = by('window-double-hung-white')
  const picture = by('window-picture-large')
  if (cls !== 'shed') {
    for (let i = 0; i < w.length; i += 1) {
      if (!glazed.has(i)) continue
      for (let s = 0; s < storeys; s += 1) {
        const ground = s === 0
        // a shopfront only goes on the ground floor of a street-facing wall; the floors above it
        // and the back of the building keep ordinary windows
        const p = shopfront && ground && (i === front || w[i].len > 8) ? store
          : cls === 'house' && ground && i === front && picture ? picture
            : hung
        if (!p) continue
        const pw = p.attach.widthM ?? 0.9
        // AN OPENING MUST FIT UNDER THE EAVES with wall left above it. When it does not, a real
        // building has a SHORTER window, not a blank elevation — dropping it outright left a 3.2 m
        // gabled bungalow (2.24 m of wall) with no windows anywhere, which is worse than massing.
        // So the sill drops first, then the glass shrinks, and only a wall with under 0.6 m of
        // room left gives up.
        const room = wallTop - s * storeyM
        let ph = p.attach.heightM ?? 1.5
        let sill = p.attach.sillM ?? 0.9
        if (sill + ph + 0.3 > room) {
          // `Math.min` because the sill only ever comes DOWN here: a shopfront sits 0.15 m off the
          // pavement by design, and a floor of 0.4 m silently threw every storefront away
          sill = Math.min(sill, Math.max(0.3, room - ph - 0.25))
          if (sill + ph + 0.25 > room) ph = room - sill - 0.25
        }
        if (ph < 0.6) continue
        // HOW FAR APART. A shopfront is a continuous glass line and the gap is a mullion; a house
        // has two or three windows an elevation with wall between them. The naive 0.8 m gap put
        // six windows along the front of a bungalow, which reads as a motel.
        const inset = shopfront && ground ? 0.4 : 0.6
        const minGap = shopfront ? (ground ? 0.3 : 1.2) : 2.5
        for (const t of spaceAlong(w[i].len, pw, { inset, minGap })) {
          if (ground && !free(i, t, pw)) continue
          const at = onWall(w[i], t)
          put(p, [at[0], at[1], base + sill + s * storeyM], w[i].yaw, i, { w: pw, h: ph })
          if (ground) reserve(i, t - pw / 2, t + pw / 2)
        }
      }
    }
  }

  /* ---- awnings over a shopfront ----------------------------------------------------------- */
  const awning = by('awning-fabric-shop')
  if (awning && shopfront && fw) {
    const aw = awning.attach.widthM ?? 3
    const sill = awning.attach.sillM ?? 2.8
    if (sill + 0.3 < wallTop) {
      for (const t of spaceAlong(fw.len, aw, { inset: 0.4, minGap: 0.6 })) {
        // `height` is the fabric, not the reach: how far it projects is `projectionM` and the
        // renderer reads that. Everything here sits ON the wall face; only the driveway, which is
        // a run out into the garden, has a position off it.
        put(awning, [...onWall(fw, t), base + sill] as [number, number, number], fw.yaw, front, { h: 0.25 })
      }
    }
  }

  /* ---- fire escape on a block, round the back --------------------------------------------- */
  const escape = by('fire-escape-landing')
  if (escape && cls === 'block' && w.length > 1 && storeys > 2) {
    const back = (front + Math.floor(w.length / 2)) % w.length
    const t = w[back].len / 2
    for (let s = 1; s < storeys; s += 1) {
      put(escape, [...onWall(w[back], t), base + s * storeyM] as [number, number, number], w[back].yaw, back, { h: 0.12 })
    }
  }

  /* ---- gutters along every eave, and a downpipe at the back corner ------------------------- */
  const eave = base + wallTop
  const gutter = by('gutter-half-round-run')
  if (gutter && cls !== 'block') {
    for (let i = 0; i < w.length; i += 1) {
      put(gutter, [...w[i].mid, eave] as [number, number, number], w[i].yaw, i, { w: w[i].len })
    }
  }
  const pipe = by('downpipe-round')
  if (pipe && cls !== 'block') {
    // the corner furthest from the street: a downpipe down the front of a house is something a
    // builder avoids and an eye notices
    let far = (front + Math.floor(w.length / 2)) % w.length
    if (street) {
      let bestD = -1
      for (let i = 0; i < w.length; i += 1) {
        const d = Math.hypot(w[i].a[0] - street[0], w[i].a[1] - street[1])
        if (d > bestD) { bestD = d; far = i }
      }
    }
    put(pipe, [w[far].a[0], w[far].a[1], base] as [number, number, number], w[far].yaw, far, { h: eave - base })
  }

  /* ---- roof: a chimney on a gabled house, a ridge vent along the ridge --------------------- */
  const cx = ring.reduce((s, p) => s + p[0], 0) / ring.length
  const cy = ring.reduce((s, p) => s + p[1], 0) / ring.length
  if (gabled && rect) {
    const ridgeYaw = -((rect.yaw_deg * Math.PI) / 180) // math angle CCW from east → yaw CW from north
    const ridgeZ = base + height
    const vent = by('roof-vent-ridge')
    if (vent) put(vent, [cx, cy, ridgeZ], ridgeYaw, -1, { w: rect.w * 0.8, h: vent.attach.heightM ?? 0.06 })
    const chimney = by('chimney-brick-residential')
    if (chimney && cls === 'house') {
      // a quarter of the way along the ridge from one end, where a flue actually comes up
      const ux = Math.cos((rect.yaw_deg * Math.PI) / 180)
      const uy = Math.sin((rect.yaw_deg * Math.PI) / 180)
      const off = rect.w * 0.25
      put(chimney, [cx + ux * off, cy + uy * off, base + height * 0.9], ridgeYaw, -1)
    }
  }

  /* ---- the things that hide round the side ------------------------------------------------ */
  const side = w.length > 1 ? (front + 1) % w.length : front
  const ac = by('ac-condenser-unit')
  if (ac && cls !== 'shed' && w[side]) {
    const t = Math.min(w[side].len - 0.8, Math.max(0.8, w[side].len * 0.7))
    put(ac, [...onWall(w[side], t), base] as [number, number, number], w[side].yaw, side)
  }
  const meter = by('meter-box-utility')
  if (meter && cls !== 'shed' && w[side]) {
    const t = Math.min(w[side].len - 0.4, Math.max(0.4, w[side].len * 0.25))
    put(meter, [...onWall(w[side], t), base + (meter.attach.sillM ?? 1.2)] as [number, number, number], w[side].yaw, side)
  }

  return sites
}

/**
 * Nearest point of road to anywhere on the site.
 *
 * Every placement rule in here hangs off "which way is the street", and on a real bake that is a
 * question asked once per building against tens of thousands of road vertices. Brute force is
 * O(buildings × vertices) and crofton-triangle alone makes that tens of millions of hypots inside
 * the frame that draws the massing, so the polylines are densified to `step` metres, bucketed into
 * a uniform grid, and searched in rings outward from the query cell.
 *
 * DENSIFIED, not just bucketed: the bake emits road coords every ~10 m on the spine but a straight
 * sibling can be two points 300 m apart, and a grid of vertices puts the whole middle of that road
 * in no cell at all — every house along it would face its far end.
 */
export class RoadIndex {
  private cells = new Map<number, [number, number][]>()
  private cell: number

  constructor(lines: [number, number][][], { cell = 24, step = 8 } = {}) {
    this.cell = cell
    for (const line of lines) {
      for (let i = 0; i < line.length; i += 1) {
        this.add(line[i])
        const next = line[i + 1]
        if (!next) continue
        const d = Math.hypot(next[0] - line[i][0], next[1] - line[i][1])
        const n = Math.floor(d / step)
        for (let k = 1; k <= n; k += 1) {
          const t = (k * step) / d
          this.add([line[i][0] + (next[0] - line[i][0]) * t, line[i][1] + (next[1] - line[i][1]) * t])
        }
      }
    }
  }

  private key(cx: number, cy: number) {
    // 16 bits each, which covers ±786 km at a 24 m cell — more than any bake
    return ((cx & 0xffff) << 16) | (cy & 0xffff)
  }

  private add(p: [number, number]) {
    const k = this.key(Math.floor(p[0] / this.cell), Math.floor(p[1] / this.cell))
    const list = this.cells.get(k)
    if (list) list.push(p)
    else this.cells.set(k, [p])
  }

  get size() {
    let n = 0
    for (const list of this.cells.values()) n += list.length
    return n
  }

  /** The nearest road point within `maxM`, or null — a building in the middle of a field has no front. */
  nearest(x: number, y: number, maxM = 80): [number, number] | null {
    const cx = Math.floor(x / this.cell)
    const cy = Math.floor(y / this.cell)
    let best: [number, number] | null = null
    let bestD = maxM * maxM
    const rings = Math.ceil(maxM / this.cell)
    for (let r = 0; r <= rings; r += 1) {
      // a hit in ring r can still be beaten by ring r+1, so one more ring runs after the first hit
      for (let gx = cx - r; gx <= cx + r; gx += 1) {
        for (let gy = cy - r; gy <= cy + r; gy += 1) {
          if (r > 0 && Math.abs(gx - cx) !== r && Math.abs(gy - cy) !== r) continue
          for (const p of this.cells.get(this.key(gx, gy)) ?? []) {
            const d = (p[0] - x) ** 2 + (p[1] - y) ** 2
            if (d < bestD) { bestD = d; best = p }
          }
        }
      }
      if (best && (r - 1) * this.cell > Math.sqrt(bestD)) break
    }
    return best
  }
}
