// The dressing kit's attachment rules.
//
// Rich, 2026-09-28: "a buildings dressing kit for windows, doors, gutters, driveways, other common
// architectural features — something we could attach to autogenerated buildings to make them feel
// alive."
//
// THE `attach` BLOCK IS THE FEATURE. Without it this is a catalogue of small meshes and the
// buildings stay dead: a window has to know it goes in a wall opening, a gutter that it follows a
// roof edge, a driveway that it meets the kerb. So these check the rules rather than the prose —
// a spec whose prompts are lovely and whose sizes are wrong produces a house with a warehouse door.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const spec = JSON.parse(readFileSync(new URL('../assetlib/specs/buildings-dressing.json', import.meta.url), 'utf8'))
const assets = spec.assets

test('every part says where it attaches', () => {
  for (const a of assets) {
    assert.ok(a.attach, `${a.id} has no attach block`)
    assert.ok(a.attach.to, `${a.id} does not say what it attaches to`)
  }
})

test('the attachment targets are ones a building generator has', () => {
  // these are the surfaces a generated building actually exposes; anything else is a part nothing
  // can place, which is the failure that looks like a complete kit and produces nothing
  const TARGETS = new Set(['wall', 'wall-corner', 'roof', 'roof-edge', 'roof-ridge', 'ground'])
  for (const a of assets) assert.ok(TARGETS.has(a.attach.to), `${a.id} attaches to ${a.attach.to}, which nothing provides`)
})

test('anything that cuts an opening gives the opening a size', () => {
  for (const a of assets.filter((x) => x.attach.opening)) {
    assert.ok(a.attach.widthM > 0, `${a.id} cuts an opening with no width`)
    assert.ok(a.attach.heightM > 0, `${a.id} cuts an opening with no height`)
    assert.ok(a.attach.sillM !== undefined, `${a.id} does not say how high off the floor it sits`)
  }
})

test('the sizes are real, in metres, and a human would recognise them', () => {
  // A door that is 2.6 m tall reads as a warehouse whatever the wall around it says — the
  // generator scales the OPENING to the part, so these numbers are the building's proportions.
  const door = assets.find((a) => a.id === 'door-front-panelled')
  assert.ok(door.attach.heightM > 1.9 && door.attach.heightM < 2.2, `a front door is about 2 m, not ${door.attach.heightM}`)
  assert.ok(door.attach.widthM > 0.7 && door.attach.widthM < 1.1)
  const garage = assets.find((a) => a.id === 'door-garage-sectional')
  assert.ok(garage.attach.heightM > 1.9 && garage.attach.heightM < 2.6, `a single garage door is about 2.1 m, not ${garage.attach.heightM}`)
  assert.ok(garage.attach.widthM > door.attach.widthM * 2, 'a garage door is much wider than a front door')
  const win = assets.find((a) => a.id === 'window-double-hung-white')
  assert.ok(win.attach.sillM > 0.6 && win.attach.sillM < 1.2, `a residential sill is about 0.9 m, not ${win.attach.sillM}`)
})

test('a storefront reaches nearly to the ground and a house window does not', () => {
  const shop = assets.find((a) => a.id === 'window-commercial-storefront')
  const house = assets.find((a) => a.id === 'window-double-hung-white')
  assert.ok(shop.attach.sillM < 0.3, 'a storefront bay starts at the pavement')
  assert.ok(house.attach.sillM > shop.attach.sillM, 'a house window sits above a storefront bay')
  assert.equal(shop.attach.storey, 'ground', 'a storefront is a ground-floor thing')
})

test('parts that run along an edge say so and are tileable', () => {
  for (const id of ['gutter-half-round-run', 'downpipe-round', 'roof-vent-ridge']) {
    const a = assets.find((x) => x.id === id)
    assert.equal(a.attach.repeat, 'run', `${id} should repeat along its edge`)
    assert.equal(a.attach.tile, true, `${id} must tile, or a long roof needs one mesh per length`)
  }
})

test('every part tells the generator what NOT to draw around it', () => {
  // The single most common failure in this pipeline: a window generated WITH a wall around it
  // cannot be placed in a wall. Every entry has to exclude its own context.
  for (const a of assets) {
    assert.ok(Array.isArray(a.avoid) && a.avoid.length, `${a.id} has no avoid list`)
  }
  const win = assets.find((a) => a.id === 'window-double-hung-white')
  assert.ok(win.avoid.some((x) => /wall/i.test(x)), 'a window must exclude the wall it goes in')
  const drive = assets.find((a) => a.id === 'driveway-concrete-apron')
  assert.ok(drive.avoid.some((x) => /kerb|road/i.test(x)), 'a driveway must exclude what it meets')
})

test('ids are usable as catalog ids', () => {
  const seen = new Set()
  for (const a of assets) {
    assert.match(a.id, /^[a-z0-9][a-z0-9-]{0,63}$/, `${a.id} is not a usable id`)
    assert.ok(!seen.has(a.id), `${a.id} appears twice`)
    seen.add(a.id)
  }
})

test('the defaults are the ones the draw step needs', () => {
  assert.equal(spec.defaults.class, 'building-dressing')
  // a flat chroma backdrop is what makes the part separable from its background at all
  assert.ok(spec.defaults.chroma, 'no chroma backdrop: the part cannot be keyed out')
  assert.ok(spec.defaults.view, 'no view angle')
})
