import { mkdirSync, writeFileSync } from 'node:fs'
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
const ROOT = new URL('../apps', import.meta.url).pathname
// family → { q: css2 query, dir: google/fonts repo path, weights }
const FAMILIES = {
  'Press Start 2P': { q: 'Press+Start+2P', lic: 'ofl/pressstart2p' },
  Yellowtail: { q: 'Yellowtail', lic: 'apache/yellowtail' },
  VT323: { q: 'VT323', lic: 'ofl/vt323' },
  Pacifico: { q: 'Pacifico', lic: 'ofl/pacifico' },
  'Racing Sans One': { q: 'Racing+Sans+One', lic: 'ofl/racingsansone' },
  Righteous: { q: 'Righteous', lic: 'ofl/righteous' },
  Audiowide: { q: 'Audiowide', lic: 'ofl/audiowide' },
  Orbitron: { q: 'Orbitron:wght@400..900', lic: 'ofl/orbitron', variable: true },
  Rajdhani: { q: 'Rajdhani:wght@500;600;700', lic: 'ofl/rajdhani' },
}
const APPS = {
  drivin: ['Yellowtail', 'VT323', 'Press Start 2P'],
  coast: ['Pacifico', 'Racing Sans One', 'Righteous', 'Press Start 2P'],
  conduit: ['Audiowide', 'Orbitron', 'Rajdhani', 'Press Start 2P'],
}
const slug = (s) => s.toLowerCase().replace(/\s+/g, '-')
const cache = new Map()
async function fetchFamily(name) {
  if (cache.has(name)) return cache.get(name)
  const f = FAMILIES[name]
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${f.q}&display=swap`, { headers: { 'user-agent': UA } })).text()
  // split into @font-face blocks, keep those preceded by "/* latin */" (or with no subset comment)
  const blocks = css.split('@font-face').slice(1)
  const faces = []
  let lastComment = ''
  for (const raw of css.split('\n')) if (/^\/\* .* \*\/$/.test(raw)) { /* tracked below */ }
  const re = /(\/\* ([a-z-]+) \*\/\s*)?@font-face \{([^}]*)\}/g
  let m
  while ((m = re.exec(css))) {
    const subset = m[2] ?? 'latin'
    if (subset !== 'latin') continue
    const body = m[3]
    const weight = /font-weight: ([0-9 ]+);/.exec(body)[1].trim()
    const url = /url\((https:[^)]+)\)/.exec(body)[1]
    if (faces.some((x) => x.url === url)) continue
    faces.push({ weight, url })
  }
  const files = []
  for (const face of faces) {
    const buf = Buffer.from(await (await fetch(face.url)).arrayBuffer())
    const fname = `${slug(name)}${faces.length > 1 ? '-' + face.weight.replace(' ', '-') : ''}.woff2`
    files.push({ ...face, fname, buf })
  }
  let lic = ''
  for (const cand of [`${f.lic}/OFL.txt`, `${f.lic}/LICENSE.txt`]) {
    const r = await fetch(`https://raw.githubusercontent.com/google/fonts/main/${cand}`)
    if (r.ok) { lic = await r.text(); break }
  }
  const out = { files, lic, variable: !!f.variable }
  cache.set(name, out)
  return out
}
for (const [app, fams] of Object.entries(APPS)) {
  const dir = `${ROOT}/${app}/public/fonts`
  mkdirSync(dir, { recursive: true })
  let css = `/* Bundled fonts for ${app}. Generated by scripts/fetch-fonts.mjs; licenses in LICENSES.txt. */\n`
  let licText = `Fonts bundled with ${app}\n=========================\n\n`
  for (const fam of fams) {
    const { files, lic, variable } = await fetchFamily(fam)
    for (const f of files) {
      writeFileSync(`${dir}/${f.fname}`, f.buf)
      css += `@font-face { font-family: "${fam}"; font-style: normal; font-weight: ${f.weight}; font-display: swap; src: url(/fonts/${f.fname}) format("woff2"); }\n`
      console.log(app, fam, f.weight, f.fname, (f.buf.length / 1024).toFixed(0) + 'KB')
    }
    licText += `----- ${fam} (${FAMILIES[fam].lic.startsWith('apache') ? 'Apache License 2.0' : 'SIL Open Font License 1.1'}) -----\n${lic || '(license text unavailable at fetch time)'}\n\n`
  }
  writeFileSync(`${dir}/fonts.css`, css)
  writeFileSync(`${dir}/LICENSES.txt`, licText)
}
