// Regenerate apps/corridor/src/ui/icons.ts from the installed Heroicons package.
//
// Heroicons ships one SVG file per icon. Pulling the package into the browser bundle would ship
// 1,300 of them to draw the twenty we use, and hand-copying path data is how you end up with an
// icon that is subtly not the one you think it is. So the path data is extracted here, at author
// time, from the real files — `npm run icons` after adding a name to NAMES below.
//
// Only the 24 px outline set is used. Solid is for state that is *on*, and we express that with
// colour instead, so one weight keeps the UI coherent.
//
//   node scripts/heroicons.mjs
//
// Heroicons is MIT, © Tailwind Labs — see CREDITS.md and node_modules/heroicons/LICENSE.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'node_modules/heroicons/24/outline')
const OUT = join(root, 'apps/corridor/src/ui/icons.ts')

/** Every icon the two corridor UIs use, grouped by where it earns its place. */
const NAMES = [
  // shell
  'bars-3', 'cog-6-tooth', 'x-mark', 'chevron-down', 'chevron-right', 'check', 'arrow-path',
  'information-circle', 'arrow-top-right-on-square', 'plus', 'minus', 'trash',
  // viewer
  'squares-2x2', 'eye', 'eye-slash', 'map', 'camera', 'link', 'adjustments-horizontal', 'play',
  'sun', 'cloud', 'globe-alt', 'map-pin', 'photo', 'viewfinder-circle', 'swatch', 'beaker', 'cube',
  // editor
  'pencil-square', 'rectangle-group', 'sparkles', 'document-arrow-down', 'lock-closed',
  'arrow-uturn-left',
  // the minimap: expand to the whole screen, back to the corner, follow the car again
  'arrows-pointing-out', 'arrows-pointing-in',
  // world editor: find a place, draw its extent, run a bake, watch it, publish it
  'magnifying-glass', 'cloud-arrow-up', 'stop', 'bolt', 'clock', 'server-stack',
  'arrow-down-tray', 'arrow-up-tray', 'queue-list', 'exclamation-triangle', 'folder-open',
  // back out of a panel, step back through a list, mark a level's finish
  'chevron-left', 'arrow-left', 'flag',
]

/*
 * IF YOU ADD A NAME HERE, RE-RUN THIS. It is not automatic and nothing checks it, and when this
 * list and icons.ts drifted apart the result was invisible rather than loud: `IconName` was
 * `keyof typeof ICONS` over a `Record<string, string>`, which is `string`, so a name this file
 * knows and icons.ts does not type-checked fine and rendered an empty <svg>. Five buttons in the
 * shipped world editor had no picture on them — back, back, back, and two finish flags — and the
 * way it was found was changing icons.ts to `satisfies` so the union is real.
 */

/** The bit between <svg …> and </svg> — one or more <path>, already stroke-styled by the wrapper. */
function inner(name) {
  const svg = readFileSync(join(SRC, `${name}.svg`), 'utf8')
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  return body
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim()
}

const entries = NAMES.map((n) => `  '${n}': '${inner(n).replace(/'/g, "\\'")}',`).join('\n')

writeFileSync(
  OUT,
  `// GENERATED by scripts/heroicons.mjs — do not edit. Add a name to that file's NAMES and re-run.
//
// Heroicons 24px outline (MIT, © Tailwind Labs). The path data is inlined so the browser downloads
// no icon font and no sprite sheet — the whole set here is about 11 kB of markup — and they inherit
// currentColor, so a button's colour is its icon's colour and there is nothing to keep in sync.

/**
 * Inner markup of each icon, keyed by its Heroicons name.
 *
 * \`satisfies\` RATHER THAN A TYPE ANNOTATION, and it is not a style preference. Annotating this
 * \`Record<string, string>\` makes \`keyof typeof ICONS\` equal to \`string\`, so \`IconName\`
 * accepted anything, a misspelled name type-checked, and \`icon()\` set \`innerHTML\` to the
 * string "undefined" — a button that renders its label and no picture, with no error anywhere.
 * Five buttons in the shipped world editor had none: three backs and two finish flags.
 * \`satisfies\` keeps the shape check AND keeps the literal key union, so the next typo is a
 * compile error.
 */
export const ICONS = {
${entries}
} satisfies Record<string, string>

export type IconName = keyof typeof ICONS

/**
 * An <svg> for \`name\`, sized in px and inheriting the current text colour.
 *
 * \`aria-hidden\` because every icon in this UI sits next to a label or inside a button that carries
 * its own \`aria-label\` — an icon that announces itself as well would say everything twice.
 */
export function icon(name: IconName, size = 20): SVGSVGElement {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  svg.setAttribute('viewBox', '0 0 24 24')
  svg.setAttribute('fill', 'none')
  svg.setAttribute('stroke', 'currentColor')
  svg.setAttribute('stroke-width', '1.5')
  svg.setAttribute('width', String(size))
  svg.setAttribute('height', String(size))
  svg.setAttribute('aria-hidden', 'true')
  svg.classList.add('icon')
  svg.innerHTML = ICONS[name]
  return svg
}
`,
  'utf8',
)

console.log(`icons.ts — ${NAMES.length} icons, ${(entries.length / 1024).toFixed(1)} kB of path data`)
