// Sprite manifest: which CC0 model renders which sprite kind, how tall it is
// in metres, and from which yaw angles (degrees; 0 = seen from behind).

import { Group, type Object3D } from 'three'
import { buildFacade, buildPrototype, buildSign, LIVERIES } from './procgen'

export interface ModelDef {
  kind: string
  /** GLB path, or empty when `build` supplies the model. */
  file: string
  build?: () => Object3D
  heightM: number
  /** Yaw angles to bake; sprites pick the nearest. */
  yaws: number[]
  /** Camera pitch angles to bake (degrees above the horizontal); default one, slightly from above. */
  pitches?: number[]
  /** Cell size in the atlas. */
  cell: number
  /** Extra uniform scale on the model before fitting (some kits are tiny). */
  fit?: number
  /**
   * Degrees to turn the model before anything looks at it. Yaw 0 means *seen from behind*, which is
   * what you want of a car driving away from you and exactly wrong for anything standing beside the
   * road: without this a diner shows the player its back wall and a light gantry shows the back of
   * its lamps. Roadside kinds carry a half turn so the side they were built to show faces the road.
   */
  spin?: number
}

/** The model as everything downstream should see it: turned to face the way its kind should face. */
export function orient(model: Object3D, def: ModelDef): Object3D {
  if (!def.spin) return model
  const g = new Group()
  g.rotation.y = (def.spin * Math.PI) / 180
  g.add(model)
  return g
}

/**
 * Smallest square texture the shelf packer fits the whole manifest into, mirroring
 * SpriteAtlas' order (big cells first). Adding views to a model grows the atlas instead
 * of silently overflowing it.
 */
export function atlasSizeFor(defs: ModelDef[], cellScale = 1): number {
  const cells = defs.flatMap((d) => d.yaws.flatMap(() => (d.pitches ?? [0]).map(() => cellSize(d, cellScale)))).sort((a, b) => b - a)
  for (const size of [512, 1024, 2048, 4096, 8192]) {
    let x = 0
    let y = 0
    let h = 0
    let fits = true
    for (const c of cells) {
      if (x + c > size) {
        x = 0
        y += h
        h = 0
      }
      if (y + c > size) {
        fits = false
        break
      }
      x += c
      h = Math.max(h, c)
    }
    if (fits) return size
  }
  return 8192
}

/** Hero views: fine steps for steering, coarse ones all the way round for the crash spin. */
export const HERO_YAWS = [0, 12, 24, 38, 60, 90, 120, 150, 180, -12, -24, -38, -60, -90, -120, -150]
/**
 * Generated by `tools/assetgen`, and a card rather than a mesh: one quad carrying the keyed
 * generated view, unlit. These kinds are baked at a single yaw through a 6.5x lens at 9 degrees
 * above the horizon, so the card foreshortens by a hundredth of its height and the sprite is the
 * picture — see tools/assetgen/card.mjs. Nothing baked at more than one yaw may use this.
 */
const G = (kind: string, file: string, heightM: number, cell = 128): ModelDef => ({ kind, file: `assets/generated/${file}.glb`, heightM, yaws: [0], cell, spin: 180 })
/** Traffic: fine flank steps for cars near your lane, quarter views for crossers, head-on, and four pitches for hills. */
export const TRAFFIC_YAWS = [0, 6, 13, 22, 35, 90, 180, -6, -13, -22, -35, -90]
export const TRAFFIC_PITCHES = [-5, 4, 13, 22]
const C = (kind: string, file: string): ModelDef => ({ kind, file: `assets/cars/${file}.glb`, heightM: 1.5, yaws: TRAFFIC_YAWS, pitches: TRAFFIC_PITCHES, cell: 128 })

export const MODELS: ModelDef[] = [
  G('palm', 'palm', 10, 192),
  G('palmTall', 'palm-tall', 13, 192),
  G('palmBend', 'palm-bend', 9.5, 192),
  G('pine', 'pine', 9, 192),
  G('pineTall', 'pine-tall', 13, 192),
  G('pineRound', 'pine-round', 8, 192),
  G('oak', 'oak', 9, 192),
  G('tree', 'tree-broadleaf', 8, 192),
  G('bush', 'bush', 1.6, 96),
  G('bushLarge', 'bush-large', 2.4, 96),
  G('rock', 'rock', 2.6, 96),
  G('rockTall', 'rock-tall', 4.2, 128),
  G('stoneTall', 'stone-tall', 3.5, 128),
  G('cactus', 'cactus', 2.4, 96),
  G('cactusTall', 'cactus-tall', 4.0, 128),
  G('flower', 'flower', 0.8, 64),
  G('stump', 'stump', 1.0, 64),
  G('billboard', 'billboard', 7.5, 256),
  G('billboardLow', 'billboard-low', 5.5, 256),
  G('lightpost', 'lightpost', 8, 128),
  G('lightpostTall', 'lightpost-tall', 10, 128),
  G('barrier', 'barrier-wall', 1.2, 96),
  G('banner', 'banner-tower', 6, 128),
  G('grandstand', 'grandstand', 7, 256),
  G('tent', 'tent', 4, 192),
  G('pitsOffice', 'pits-office', 6, 256),
  G('gantry', 'overhead-gantry', 8.5, 256),
  // Hero prototypes, one per livery; the chase view picks the selected one.
  ...Object.entries(LIVERIES).map(([id, l]): ModelDef => ({ kind: `hero_${id}`, file: '', build: () => buildPrototype(l), heightM: 1.1, yaws: HERO_YAWS, cell: 288 })),
  { kind: 'formula', file: 'assets/cars/race.glb', heightM: 1.1, yaws: HERO_YAWS, cell: 288 },
  // Roadside architecture and signage.
  G('diner', 'diner', 6.4, 256),
  G('block', 'block-concrete', 15, 192),
  G('facade1', 'facade-shopfront', 14.4, 192),
  G('facade2', 'facade-office', 17.8, 192),
  G('facade3', 'facade-lowrise', 11, 160),
  G('facade4', 'facade-tall', 21.2, 224),
  { kind: 'facadeLit1', file: '', build: () => buildFacade(8, 4, 0x4a4a5a, 0xff5fd2, true), heightM: 17.8, yaws: [0], cell: 192, spin: 180 },
  G('facadeLit2', 'facade-neon-arcade', 14.4, 192),
  G('block2', 'block-brick', 11, 192),
  G('motel', 'motel-strip', 7.6, 256),
  G('gas', 'gas-station', 4.6, 256),
  G('tower', 'tower', 37, 256),
  G('tower2', 'tower-low', 25, 256),
  { kind: 'signCoast', file: '', build: () => buildSign('COAST HWY 1', '#ffffff', '#1a5a2a'), heightM: 7.3, yaws: [0], cell: 192, spin: 180 },
  { kind: 'signDrive', file: '', build: () => buildSign('DRIVE SAFE', '#ffe28a', '#7a1a1a'), heightM: 7.3, yaws: [0], cell: 192, spin: 180 },
  { kind: 'signBay', file: '', build: () => buildSign('NEON BAY 12', '#ff5fd2', '#101030'), heightM: 7.3, yaws: [0], cell: 192, spin: 180 },
  G('arch', 'arch', 10.2, 256),
  C('sedan', 'sedan'),
  C('sedanSports', 'sedan-sports'),
  C('suv', 'suv'),
  C('van', 'van'),
  C('truck', 'truck'),
  C('taxi', 'taxi'),
  C('police', 'police'),
  C('delivery', 'delivery'),
]

/** Width in road-halves is derived from the baked aspect; these are height metres for the sim's hit tests elsewhere. */
export const MODEL_BY_KIND: Record<string, ModelDef> = Object.fromEntries(MODELS.map((m) => [m.kind, m]))

/** A model's cell at a given scale. Never below 16 px, or the sprite is mush. */
export function cellSize(def: ModelDef, cellScale: number): number {
  return Math.max(16, Math.round((def.cell * cellScale) / 2) * 2)
}

/** Atlas texture size for the current manifest at full cell size (see atlasSizeFor). */
export const ATLAS_SIZE = atlasSizeFor(MODELS)
