// The engines that ship inside the wasm.
//
// Generated by scripts/build-wasm.mjs from the upstream asset tree, using upstream's own rule: a
// script is directly runnable only when it declares the conventional `public node main`. Helper
// modules such as radial.mr are imports and are not listed.

import entries from '../wasm/engines.json'

export interface CatalogEntry {
  /** Path to pass to `EngineSim.load`, relative to the embedded asset root. */
  path: string
  /** Who made it — the upstream directory, e.g. "Bmw", "Atg Video 2". */
  group: string
  /** The engine, e.g. "Gm Ls". */
  name: string
}

export const ENGINES: readonly CatalogEntry[] = entries as CatalogEntry[]

/** The catalog arranged for a picker. */
export function enginesByGroup(): Map<string, CatalogEntry[]> {
  const groups = new Map<string, CatalogEntry[]>()
  for (const entry of ENGINES) {
    const bucket = groups.get(entry.group)
    if (bucket) bucket.push(entry)
    else groups.set(entry.group, [entry])
  }
  return groups
}
